copy from previous changes

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -3,6 +3,34 @@ on:
   pull_request:
   push:
     branches:
+<<<<<<< HEAD
+      - main
+      - '5.0'
+      - 'v5.*'
+      - 3.x
+      - 2.x
+      - 'renovate/*'
+env:
+  FORCE_COLOR: 1
+concurrency:
+  group: ${{ github.head_ref || github.run_id }}
+  cancel-in-progress: true
+jobs:
+  lint:
+    runs-on: ubuntu-18.04
+    if: github.event_name == 'push' || (github.event_name == 'pull_request' && !startsWith(github.head_ref, 'renovate/'))
+    name: Lint
+    steps:
+      - uses: actions/checkout@v2
+      - uses: actions/setup-node@v2
+        env:
+          FORCE_COLOR: 0
+        with:
+          node-version: '14.17.0'
+          cache: yarn
+      - run: yarn
+      - run: yarn lint
+=======
       - "v4.*"
       - "5.0"
       - "multiple-newsletters"
@@ -22,12 +50,109 @@ jobs:
       - run: yarn
       - run: grunt shell:ember:prod
 
+>>>>>>> admin/main
       - uses: daniellockyer/action-slack-build@master
         if: failure() && github.event_name == 'push' && github.ref == 'refs/heads/main'
         with:
           status: ${{ job.status }}
         env:
           SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
+<<<<<<< HEAD
+
+  migrations:
+    runs-on: ubuntu-18.04
+    defaults:
+      run:
+        working-directory: ghost/core
+    if: github.event_name == 'push' || (github.event_name == 'pull_request' && !startsWith(github.head_ref, 'renovate/'))
+    strategy:
+      matrix:
+        env:
+          - DB: sqlite3
+            DB_CLIENT: sqlite3
+          - DB: mysql5
+            DB_CLIENT: mysql
+          - DB: mysql8
+            DB_CLIENT: mysql
+    env:
+      database__client: ${{ matrix.env.DB_CLIENT }}
+    name: Migrations (${{ matrix.env.DB }})
+    steps:
+      - uses: actions/checkout@v2
+        with:
+          fetch-depth: 0
+          submodules: true
+      - uses: actions/setup-node@v2
+        env:
+          FORCE_COLOR: 0
+        with:
+          node-version: '14.17.0'
+          cache: yarn
+
+      - name: Shutdown MySQL
+        run: sudo service mysql stop
+        if: matrix.env.DB == 'mysql5' || matrix.env.DB == 'mysql8'
+
+      - uses: daniellockyer/mysql-action@main
+        if: matrix.env.DB == 'mysql5'
+        with:
+          mysql version: '5.7'
+          mysql database: 'ghost_testing'
+          mysql root password: 'root'
+
+      - uses: daniellockyer/mysql-action@main
+        if: matrix.env.DB == 'mysql8'
+        with:
+          authentication plugin: 'caching_sha2_password'
+          mysql version: '8.0'
+          mysql database: 'ghost_testing'
+          mysql root password: 'root'
+
+      - name: Set env vars (SQLite)
+        if: contains(matrix.env.DB, 'sqlite')
+        run: echo "database__connection__filename=/dev/shm/ghost-test.db" >> $GITHUB_ENV
+
+      - name: Set env vars (MySQL)
+        if: contains(matrix.env.DB, 'mysql')
+        run: |
+          echo "database__connection__host=127.0.0.1" >> $GITHUB_ENV
+          echo "database__connection__user=root" >> $GITHUB_ENV
+          echo "database__connection__password=root" >> $GITHUB_ENV
+          echo "database__connection__database=ghost_testing" >> $GITHUB_ENV
+
+      - run: yarn
+      - run: |
+          node index.js &
+          sleep 20 && { kill $! && wait $!; } 2>/dev/null
+
+      - run: sqlite3 ${{ env.database__connection__filename }} "DELETE FROM migrations WHERE version LIKE '5.%';"
+        if: matrix.env.DB == 'sqlite3'
+      - run: mysql -h127.0.0.1 -uroot -proot ghost_testing -e "DELETE FROM migrations WHERE version LIKE '5.%';"
+        if: matrix.env.DB == 'mysql5' || matrix.env.DB == 'mysql8'
+
+      - run: yarn knex-migrator migrate --force
+
+  unit-tests:
+    runs-on: ubuntu-18.04
+    if: github.event_name == 'push' || (github.event_name == 'pull_request' && !startsWith(github.head_ref, 'renovate/'))
+    strategy:
+      matrix:
+        node: [ '14.17.0', '16.13.0' ]
+    name: Unit Tests (Node ${{ matrix.node }})
+    steps:
+      - uses: actions/checkout@v2
+      - uses: actions/setup-node@v2
+        env:
+          FORCE_COLOR: 0
+        with:
+          node-version: ${{ matrix.node }}
+          cache: yarn
+
+      - run: yarn
+      - run: yarn test
+
+      - uses: codecov/codecov-action@v2
+=======
   lint:
     runs-on: ubuntu-18.04
     if: github.event_name == 'push' || (github.event_name == 'pull_request' && !startsWith(github.head_ref, 'renovate/'))
@@ -41,6 +166,7 @@ jobs:
       - run: yarn
       - run: yarn lint:js
       - run: yarn lint:hbs
+>>>>>>> admin/main
 
       - uses: daniellockyer/action-slack-build@master
         if: failure() && github.event_name == 'push' && github.ref == 'refs/heads/main'
@@ -48,6 +174,163 @@ jobs:
           status: ${{ job.status }}
         env:
           SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
+<<<<<<< HEAD
+
+  database-tests:
+    runs-on: ubuntu-18.04
+    defaults:
+      run:
+        working-directory: ghost/core
+    if: github.event_name == 'push' || (github.event_name == 'pull_request' && !startsWith(github.head_ref, 'renovate/'))
+    strategy:
+      matrix:
+        node: [ '14.17.0', '16.13.0' ]
+        env:
+          - DB: sqlite3
+            NODE_ENV: testing
+          - DB: mysql5
+            NODE_ENV: testing-mysql
+          - DB: mysql8
+            NODE_ENV: testing-mysql
+    env:
+      DB: ${{ matrix.env.DB }}
+      NODE_ENV: ${{ matrix.env.NODE_ENV }}
+    name: Database Tests (Node ${{ matrix.node }}, ${{ matrix.env.DB }})
+    steps:
+      - uses: actions/checkout@v2
+      - uses: actions/setup-node@v2
+        env:
+          FORCE_COLOR: 0
+        with:
+          node-version: ${{ matrix.node }}
+          cache: yarn
+
+      - name: Shutdown MySQL
+        run: sudo service mysql stop
+        if: matrix.env.DB == 'mysql5' || matrix.env.DB == 'mysql8'
+
+      - uses: daniellockyer/mysql-action@main
+        if: matrix.env.DB == 'mysql5'
+        with:
+          mysql version: '5.7'
+          mysql database: 'ghost_testing'
+          mysql root password: 'root'
+
+      - uses: daniellockyer/mysql-action@main
+        if: matrix.env.DB == 'mysql8'
+        with:
+          authentication plugin: 'caching_sha2_password'
+          mysql version: '8.0'
+          mysql database: 'ghost_testing'
+          mysql root password: 'root'
+
+      - run: yarn
+
+      - run: date +%s > ${{ runner.temp }}/startTime # Get start time for test suite
+
+      - name: Set env vars (SQLite)
+        if: contains(matrix.env.DB, 'sqlite')
+        run: echo "database__connection__filename=/dev/shm/ghost-test.db" >> $GITHUB_ENV
+
+      - name: Set env vars (MySQL)
+        if: contains(matrix.env.DB, 'mysql')
+        run: echo "database__connection__password=root" >> $GITHUB_ENV
+
+      - name: Run tests
+        run: yarn test:ci
+
+      # Get runtime in seconds for test suite
+      - run: |
+          startTime="$(cat ${{ runner.temp }}/startTime)"
+          endTime="$(date +%s)"
+          echo "test_time=$(($endTime-$startTime))" >> $GITHUB_ENV
+
+      # Continue on error if TailScale service is down
+      - name: Tailscale Action
+        timeout-minutes: 2
+        continue-on-error: true
+        if: (github.event_name == 'push' && github.repository_owner == 'TryGhost') || (github.event_name == 'pull_request' && startsWith(github.head_ref, 'TryGhost/'))
+        uses: tailscale/github-action@v1
+        with:
+          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}
+
+      # Report time taken to metrics service
+      # Continue on error if previous TailScale step fails
+      - uses: sam-lord/action-trigger-metric@main
+        timeout-minutes: 1
+        continue-on-error: true
+        if: (github.event_name == 'push' && github.repository_owner == 'TryGhost') || (github.event_name == 'pull_request' && startsWith(github.head_ref, 'TryGhost/'))
+        with:
+          metricName: 'test-time'
+          metricValue: ${{ env.test_time }}
+          configuration: |
+            {
+              "metrics": {
+                "transports": ["elasticsearch"],
+                "metadata": {
+                  "database": "${{ matrix.env.DB }}",
+                  "node": "${{ matrix.node }}"
+                }
+              },
+              "elasticsearch": {
+                "host": "${{ secrets.ELASTICSEARCH_HOST }}",
+                "username": "${{ secrets.ELASTICSEARCH_USERNAME }}",
+                "password": "${{ secrets.ELASTICSEARCH_PASSWORD }}"
+              }
+            }
+
+      - uses: daniellockyer/action-slack-build@master
+        if: failure() && github.event_name == 'push' && github.ref == 'refs/heads/main'
+        with:
+          status: ${{ job.status }}
+        env:
+          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
+
+  ghost-cli:
+    name: Ghost-CLI
+    if: false
+    runs-on: ubuntu-18.04
+    defaults:
+      run:
+        working-directory: ghost/core
+    steps:
+      - uses: actions/checkout@v2
+        with:
+          fetch-depth: 0
+          submodules: true
+      - uses: actions/setup-node@v2
+        env:
+          FORCE_COLOR: 0
+        with:
+          node-version: '14.17.0'
+          cache: yarn
+      - run: npm install -g ghost-cli@latest
+      - run: npm --no-git-tag-version version minor # We need to artificially bump the minor version to get migrations to run
+
+      - run: zip -r ghost.zip .
+
+      - name: Clean Install
+        run: |
+          DIR=$(mktemp -d)
+          ghost install local -d $DIR --zip $(pwd)/ghost.zip
+
+      - name: Latest Release
+        run: |
+          DIR=$(mktemp -d)
+          ghost install local -d $DIR
+          ghost update -d $DIR --zip $(pwd)/ghost.zip
+
+      - name: Update from latest v3
+        run: |
+          DIR=$(mktemp -d)
+          ghost install v3 --local -d $DIR
+          ghost update -f -d $DIR --zip $(pwd)/ghost.zip
+
+      - name: Print debug logs
+        if: failure()
+        run: |
+          [ -f ~/.ghost/logs/*.log ] && cat ~/.ghost/logs/*.log
+=======
   test:
     runs-on: ubuntu-18.04
     if: github.event_name == 'push' || (github.event_name == 'pull_request' && !startsWith(github.head_ref, 'renovate/'))
@@ -74,6 +357,7 @@ jobs:
       # Merge coverage reports and upload
       - run: yarn ember coverage-merge
       - uses: codecov/codecov-action@v3
+>>>>>>> admin/main
 
       - uses: daniellockyer/action-slack-build@master
         if: failure() && github.event_name == 'push' && github.ref == 'refs/heads/main'
@@ -84,7 +368,11 @@ jobs:
 
   canary:
     runs-on: ubuntu-18.04
+<<<<<<< HEAD
+    needs: [lint, migrations, unit-tests, database-tests]
+=======
     needs: [lint, test, prod-build]
+>>>>>>> admin/main
     if: github.event_name == 'push' && github.ref == 'refs/heads/main'
     name: Canary
     steps:
@@ -92,5 +380,9 @@ jobs:
         uses: benc-uk/workflow-dispatch@v1
         with:
           workflow: Canary Build
+<<<<<<< HEAD
+          token: ${{ secrets.RELEASE_TOKEN }}
+=======
           repo: TryGhost/Ghost
           token: ${{ secrets.WORKFLOW_TOKEN }}
+>>>>>>> admin/main
